# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AS207960
email: info@as207960.net
url: "https://as207960.net"
twitter:
  username: AS_207960
github:
  username: as207960
logo: /assets/img/logo.svg
social:
  links:
    - https://github.com/as207960
    - https://twitter.com/AS_207960
    - https://www.linkedin.com/company/as207960/
tagline: AS207960 is an UK based ASN, the IP networking side of Glauca
description: Looking for our customer facing site? It's <a href="https://glau.ca">here</a>


include:
  - ".well-known"
  - "favicon.svg"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate

paginate_path: /posts/page:num/
permalink: /posts/:title

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
